// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

import (
	"context"
	"fmt"

	"rollbringer/pkg/domain"
)

var foo = templ.NopComponent

var F = fmt.Sprintf

func GetUser(ctx context.Context) *domain.User {
	user, _ := ctx.Value("user").(*domain.User)
	return user
}

func GetSession(ctx context.Context) *domain.Session {
	session, _ := ctx.Value("session").(*domain.Session)
	return session
}

func GetGame(ctx context.Context) *domain.Game {
	game, _ := ctx.Value("game").(*domain.Game)
	return game
}

func GetGames(ctx context.Context) []*domain.Game {
	games, _ := ctx.Value("games").([]*domain.Game)
	return games
}

func GetPDFs(ctx context.Context) []*domain.PDF {
	pdfs, _ := ctx.Value("pdfs").([]*domain.PDF)
	return pdfs
}
