version: "3.7"

services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: Docker/app.dockerfile
    environment:
      APP_PORT: "3000"
      APP_USERS_GOOGLE_CLIENT_ID: ${APP_USERS_GOOGLE_CLIENT_ID}
      APP_USERS_GOOGLE_CLIENT_SECRET: ${APP_USERS_GOOGLE_CLIENT_SECRET}
      APP_USERS_REDIRECT_URL: ${APP_USERS_REDIRECT_URL}
      APP_USERS_SESSION_TIMEOUT: "15min"
      APP_NATS_EMBEDDED_SERVER_STARTUP_TIMEOUT: "5sec"
      APP_POSTGRES_ADDRESS: "postgresql://postgres:abc123@database:5432?sslmode=disable"
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    container_name: database
    build:
      context: ../
      dockerfile: Docker/postgres.dockerfile
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
