services:
  pubsub:
    container_name: pubsub
    image: nats
    ports:
      - 4222:4222

  database:
    container_name: database
    build:
      context: ../
      dockerfile: Docker/postgres.dockerfile
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
