services:

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/pg-data:/var/lib/postgresql/data
      - ./Docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
