// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: google_users.sql

package queries

import (
	"context"
)

const insertGoogleUser = `-- name: InsertGoogleUser :execrows
INSERT INTO google_users (google_id, given_name, email)
VALUES ($1, $2, $3)
ON CONFLICT (google_id) DO NOTHING
`

type InsertGoogleUserParams struct {
	GoogleID  string `json:"google_id"`
	GivenName string `json:"given_name"`
	Email     string `json:"email"`
}

func (q *Queries) InsertGoogleUser(ctx context.Context, arg *InsertGoogleUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertGoogleUser, arg.GoogleID, arg.GivenName, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGoogleUser = `-- name: UpdateGoogleUser :execrows
UPDATE google_users
SET
    given_name = coalesce($1, given_name),
    email = coalesce($2, email)
WHERE google_id = $3
`

type UpdateGoogleUserParams struct {
	GivenName string `json:"given_name"`
	Email     string `json:"email"`
	GoogleID  string `json:"google_id"`
}

func (q *Queries) UpdateGoogleUser(ctx context.Context, arg *UpdateGoogleUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGoogleUser, arg.GivenName, arg.Email, arg.GoogleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
