// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/Sidney-Bernardin/Rollbringer/server"
	"github.com/jackc/pgx/v5/pgtype"
)

type GoogleUser struct {
	GoogleID  string           `json:"google_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	GivenName string           `json:"given_name"`
	Email     string           `json:"email"`
}

type User struct {
	ID             server.UUID      `json:"id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	GoogleID       *string          `json:"google_id"`
	Username       string           `json:"username"`
	ProfilePicture string           `json:"profile_picture"`
}
