// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package queries

import (
	"context"

	"github.com/Sidney-Bernardin/Rollbringer/server"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, google_id, username, profile_picture)
VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID             server.UUID `json:"id"`
	GoogleID       *string     `json:"google_id"`
	Username       string      `json:"username"`
	ProfilePicture string      `json:"profile_picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.GoogleID,
		arg.Username,
		arg.ProfilePicture,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, google_id, username, profile_picture FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID server.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.Username,
		&i.ProfilePicture,
	)
	return &i, err
}

const getUserID = `-- name: GetUserID :one
SELECT id FROM users
WHERE google_id = $1
`

func (q *Queries) GetUserID(ctx context.Context, googleID *string) (server.UUID, error) {
	row := q.db.QueryRow(ctx, getUserID, googleID)
	var id server.UUID
	err := row.Scan(&id)
	return id, err
}
